- Cargo.toml
This PR is removing some unneeded deps
> chore: remove unused agglayer crates deps

- .github/workflows/doc.yml
- crates/agglayer-prover/src/fake.rs
This PR is fixing the doc generation
> fix: doc generation

- crates/prover-engine/src/lib.rs
This PR is adding the different method to configure the different rpc ports.
> fix: expose method for endpoint config

- Cargo.lock
- Cargo.toml
- crates/aggchain-proof-builder/Cargo.toml
- crates/aggchain-proof-builder/src/config.rs
- crates/aggchain-proof-builder/src/lib.rs
- crates/aggchain-proof-builder/src/provider/mod.rs
- crates/aggchain-proof-service/Cargo.toml
- crates/aggchain-proof-service/src/error.rs
- crates/aggchain-proof-service/src/service.rs
- crates/aggkit-prover-config/tests/snapshots/validate_deserialize__empty_rpcs.snap
- crates/aggkit-prover-config/tests/snapshots/validate_deserialize__prover_grpc_max_decoding_message_size.snap
- crates/aggkit-prover/src/rpc.rs
- crates/agglayer-prover-types/Cargo.toml
- crates/agglayer-prover-types/src/error.rs
- crates/agglayer-prover-types/src/lib.rs
- crates/agglayer-prover/src/rpc.rs
- crates/proposer-client/src/lib.rs
- crates/proposer-client/src/rpc.rs
- crates/proposer-service/Cargo.toml
- crates/proposer-service/src/config.rs
- crates/proposer-service/src/error.rs
- crates/proposer-service/src/lib.rs
- crates/prover-alloy/Cargo.toml
- crates/prover-alloy/src/lib.rs
- crates/prover-executor/Cargo.toml
- crates/prover-executor/src/error.rs
- crates/prover-executor/src/lib.rs
This PR is refactoring the tower services pipeline and remove a leftover agglayer-prover-types dependency.
It also introduce a new crate to manage alloy connection/utils to share with multiple other crates (name can be rework).
> feat: updating tower services

- .github/workflows/test.yml
> build: update ci jobs

- crates/aggchain-proof-builder/src/lib.rs
- crates/aggchain-proof-service/src/service.rs
- crates/proposer-client/src/lib.rs
- crates/proposer-service/src/lib.rs
- crates/proposer-service/src/tests/mod.rs
> refactor: rename `agg_span_proof` -> `aggregation_proof`

- Cargo.lock
- crates/aggchain-proof-core/src/full_execution_proof.rs
- crates/aggchain-proof-core/src/lib.rs
- crates/aggchain-proof-core/src/vkey_hash.rs
- crates/aggkit-prover-types/Cargo.toml
- crates/aggkit-prover-types/src/lib.rs
- crates/aggkit-prover-types/src/vkey_hash.rs
> refactor: introduce the `VKeyHash` type

- .github/workflows/release.yml
Update docker image name for aggkit-prover
> refactor: update docker image name

- crates/aggkit-prover/src/lib.rs
This PR addresses some fixes for integration
> fix: add missing socket addr

- Cargo.lock
- Cargo.toml
This PR is fixing the interop version to 0.1.0 for safety.
> feat: fixing the interop version

- Cargo.lock
- Cargo.toml
- crates/aggchain-proof-builder/src/lib.rs
- crates/aggchain-proof-core/Cargo.toml
- crates/aggchain-proof-core/src/bridge/inserted_ger.rs
- crates/aggchain-proof-core/src/bridge/mod.rs
- crates/aggchain-proof-core/src/full_execution_proof.rs
- crates/aggchain-proof-core/src/proof.rs
- crates/aggchain-proof-program/Cargo.lock
re-arrange deps to have aggchain proof program compile in zkvm
> chore: make aggchain proof elf compile

- crates/aggchain-proof-builder/src/error.rs
- crates/aggchain-proof-builder/src/lib.rs
- crates/prover-executor/src/lib.rs
Fix the call of the prover executor.
> fix: service ready

- crates/aggchain-proof-builder/src/lib.rs
> fix: optimize vkey generation

- crates/aggkit-prover/src/rpc.rs
Remove `request` argument from instrument list
> refactor: add request to skip list in instrument macro

- crates/proposer-client/src/mock_prover.rs
> fix: adjust to newer error codes in op-succinct

- .github/workflows/coverage.yml
> feat: re-enable coverage now that the repo is public

- codecov.yml
> feat: ignore coverage for generated code

- crates/prover-config/src/lib.rs
- crates/prover-executor/src/lib.rs
Remove the config and references to the unsupported GPU prover.
> chore: remove config related to unsupported gpu prover

- .github/workflows/test.yml
- scripts/make/Makefile.elf.toml
* Make the elf checking run on the `push` event.
* Use a fixed version for `cargo prove`.
> ci: elf checking fixes

- crates/aggchain-proof-contracts/src/config.rs
- crates/aggchain-proof-core/src/bridge/mod.rs
Appease the new clippy version. Unblocks CI.
> chore: fix clippy

- Cargo.lock
- Cargo.toml
Companion of agglayer/interop#68.
> chore: update agglayer-primitives to a more recent version

- crates/aggkit-prover/src/lib.rs
- crates/agglayer-prover/src/lib.rs
Exit with error in aggkit-prover and agglayer-prover.
Fixes https://github.com/agglayer/provers/issues/206
> fix: exit with error
